services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    networks:
      - selenium-network

  chrome-node:
    image: selenium/node-chrome:latest
    container_name: chrome-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-network

  firefox-node:
    image: selenium/node-firefox:latest
    container_name: firefox-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-network

  test-runner:
    build: .
    container_name: test-runner
    depends_on:
      - selenium-hub
      - chrome-node
      - firefox-node
    environment:
      - BROWSER_NAME=chrome
      - SELENIUM_HUB_URL=http://selenium-hub:4444
      - TEST_PATTERN=Automation
    networks:
      - selenium-network
    volumes:
      - ./allure-reports:/usr/src/app/target/site/allure-maven-plugin

networks:
  selenium-network:
    driver: bridge